seleniumhub:
  image: selenium/hub
  ports:
    - 4444:4444

firefoxnode:
  image: selenium/node-firefox-debug
  ports:
    - 6200
  links:
    - seleniumhub:hub

chromenode:
  image: selenium/node-chrome-debug
  ports:
    - 5910
  links:
    - seleniumhub:hub

appium_devices:
    image: appium/appium
    depends_on:
      - seleniumhub
    network_mode: "service:seleniumhub"
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - CONNECT_TO_GRID=True
      - SELENIUM_HOST=seleniumhub